HH-client-manager/Models/Database/PCLAssessment.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Threading.Tasks;

namespace HH_client_manager.Models.Database
{
    public class PCLAssessment
{
        [DisplayName("PCL Sequence Number")]
        public int Sequence_number { get; set; }

        [DisplayName("Client ID")]
        public string ClientID { get; set; }

        [DisplayName("Assessment Date")]
        public DateTime Date { get; set; }

        [DisplayName("Assessment Type")]
        public string Assessment_Type { get; set; }

        [DisplayName("Event Description")]
        public string Event_description { get; set; }

        [DisplayName("Event Date")]
        public DateTime? Event_date { get; set; }

        [DisplayName("Edited By")]
        public string Edited_by { get; set; }

        [DisplayName("Edit Date")]
        public DateTime Edit_date { get; set; }





    }
}

HH-client-manager/Models/Database/PCLAssessmentViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HH_client_manager.Models.Database;

namespace HH_client_manager
{
    public class PCLAssessmentViewModel
    {
        public PCLAssessment pCLAssessment { get; set; }
        public List<PCLDetailDataEntry> pCLDetailDataEntry { get; set; }
        public List<PCLScale> pCLScale { get; set; }

        public PCLAssessmentViewModel()
        {
            pCLDetailDataEntry = new List<PCLDetailDataEntry>();
            pCLScale = new List<PCLScale>();
        }
    }//end of PCLAssessmentViewModel


}//end of namespace

HH-client-manager/Controllers/PCLAssessmentController.cs
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using HH_client_manager.Models.Database;
using System.Data.SqlClient;
using HH_client_manager.Controllers;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace HH_client_manager
{
    public class PCLAssessmentController : Controller
    {

        // GET: /<controller>/
        public IActionResult Index()
        {



            return View();
        }//end of Index

        [HttpGet]
        public IActionResult createPCLAssessment()
        {
            PCLAssessmentDataAccessLayer accessLayer = new PCLAssessmentDataAccessLayer();

            PCLAssessmentViewModel PCLData = new PCLAssessmentViewModel();
            PCLData.pCLDetailDataEntry = accessLayer.GetPCLDetailDataEntry();
            PCLData.pCLScale = accessLayer.GetPCLScale();

            PCLData.pCLAssessment = new Models.Database.PCLAssessment();

            return View(PCLData);

        }//end CreateAssessment GET


        [HttpPost]
        public IActionResult CreatePCLAssessment(PCLAssessmentViewModel pCLData)
        {
            if (ModelState.IsValid)
            {
                PCLAssessmentDataAccessLayer accessLayer = new PCLAssessmentDataAccessLayer();

                PCLAssessment pCLAssessment = pCLData.pCLAssessment;

                int sequenceNumber = accessLayer.CreatePCLAssessment(pCLAssessment);

                foreach (PCLDetailDataEntry detail in pCLData.pCLDetailDataEntry)
                {
                    accessLayer.WritePCLDetailRecord(sequenceNumber, detail);
                }//end foreach
            }//end if

            return View(pCLData);
        }//end CreateAssessment Post


    }//end of PCLAssessmentController
}//end of namespace

HH-client-manager/Views/PCLAssessment/CreatePCLAssessment.cshtml
@using HH_client_manager.Models.Database;
@model PCLAssessmentViewModel;


@{
    ViewData["Title"] = "Create PCL Assessment";
}

<h2>PCL Assessment</h2>

    @*action, then the controller name*@

@using (Html.BeginForm("CreatePCLAssessment", "PCLAssessment"))
{


    PCLAssessment pCLAssessment = Model.pCLAssessment;



        <div class="editor-label">
            @Html.LabelFor(model => pCLAssessment.ClientID, "Client ID: ")
        </div> <!--end of "form-group" div for Patient Name-->

        <div class="col-md-offset-0">

            @Html.EditorFor(model => pCLAssessment.ClientID)

            @Html.ValidationMessageFor(model => pCLAssessment.ClientID, "", new { @class = "text-danger" })

        </div> <!--end of "col-md-10" div for Patient Name-->

        <br />

        <div class="editor-label">

            @Html.LabelFor(model => pCLAssessment.Date, "Date: ")

        </div><!--end of "form-group" div for Today's Date-->

        <div class="col-md-offset-0">

            @Html.TextBoxFor(Model => pCLAssessment.Date, new { type = "date" })

        </div><!--end of "col-md-10" div for Today's Date-->


        <br />
        <br />

        <p>
            If an event listed on the Life Events Checklist <strong>happened to you </strong> or you <strong>witnessed it, </strong>
            please complete the items below. If more than one event happened, please choose the one that is <strong>most troublesome to you now.</strong>
        </p>

        <br />
        <br />

        <div class="editor-label">
            @Html.LabelFor(model => pCLAssessment.Event_description, "Event: ")

            <div class="col-md-offset-0">

                @Html.EditorFor(model => pCLAssessment.Event_description)

                @Html.ValidationMessageFor(model => pCLAssessment.Event_description, "", new { @class = "text-danger" })

            </div> <!--end of "col-md-10" div for Event-->

        </div> <!--end of "form-group" div for Event-->

        <div class="editor-label">

            @Html.LabelFor(model => pCLAssessment.Event_date, "Date: ")

            <div class="col-md-offset-0">

                @Html.TextBoxFor(Model => pCLAssessment.Event_date, new { type = "date" })

            </div><!--end of "col-md-10" div for Event Date-->


        </div><!--end of "form-group" div for Event Date-->

        <div class="editor-label">

            @Html.LabelFor(model => pCLAssessment.Assessment_Type, "Assessment Type: ")

            <div class="col-md-offset-0">

                @Html.TextBoxFor(Model => pCLAssessment.Assessment_Type, new { @class = "text-danger" })

            </div><!--end of "col-md-10" div for Assessment Type-->


        </div><!--end of "form-group" div for Assessment Type-->

        <div class="editor-label">

            @Html.LabelFor(model => pCLAssessment.Edited_by, "Edited By: ")

            <div class="col-md-offset-0">

                @Html.TextBoxFor(Model => pCLAssessment.Edited_by, new { @class = "text-danger" })

            </div><!--end of "col-md-10" div for Edited By -->


        </div><!--end of "form-group" div for Edited By-->

        <div class="editor-label">

            @Html.LabelFor(model => pCLAssessment.Edit_date, "Date: ")

            <div class="col-md-offset-0">

                @Html.TextBoxFor(Model => pCLAssessment.Edit_date, new { type = "date" })

            </div><!--end of "col-md-10" div for Edit Date-->


        </div><!--end of "form-group" div for Edit Date-->





   <table>



        <tr>

             <th>Number</th>

             <th>Bothered By</th>

             <th>Scale</th>


        </tr>


    

                @for ( int i =0; i < Model.pCLDetailDataEntry.Count; i++)
                {
        <tr>
            <td>@Html.DisplayFor(model => model.pCLDetailDataEntry[i].Bothered_by_order)</td>
            <td>@Html.DisplayFor(model => model.pCLDetailDataEntry[i].Bothered_by_Description)</td>
            <td>@Html.TextBoxFor(model => model.pCLDetailDataEntry[i].Scale_number)
                

            
                </td>

            </tr>

               
              
                 }


   </table>
       
    <br />
    <br />

    <input type="submit" value="Submit Form" />

}<!-- end of form-->